import Head from 'next/head'
import { useState } from 'react'

export default function Home(opensea) {
  const [creatures, setCreatures] = useState()
  const [data, setData] = useState()

  const handlesubmit = async (event) =>   {
    event.preventDefault();
    try {
      const opsenseacall = await fetch("http://localhost:3000/nefturian/" + creatures, {
        method: 'GET',
        headers: {
          accept: 'application/json',
        },
      });
      const opensea = await opsenseacall.json()
      setData(opensea)
      console.log(opensea)
    }
    catch (error) {
      console.log("Error: ", error)
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Title</h1>
        <input type="text" value={creatures || ""} onChange={ (e) => setCreatures(e.target.value)}></input>
        <button onClick={handlesubmit}>Link your creatures</button>
         {data && <div><p>{data.name}</p> <p> {data.description}</p></div>}
      </main>
    </>
  )
}
